#!/bin/bash

# --- Core Initialization ---

setup_project_dir() {
  local dir="$1"
  local name="$2"
  
  if [[ -d "$dir" && "$(ls -A "$dir" 2>/dev/null)" ]]; then
    if [[ "${SILENT_MODE:-false}" != "true" ]]; then
      log_warn "Target directory '$dir' is not empty."
      echo -e -n "${YELLOW}  Continue and potentially overwrite files? (y/N): ${RESET}"
      read -r confirm < /dev/tty
      if [[ ! "$confirm" =~ ^[Yy]$ ]]; then
        fatal_error "Aborted by user."
      fi
    fi
    
    if [[ "$dir" != "$(pwd)" ]]; then
        rm -rf "$dir"
        mkdir -p "$dir"
    fi
  else
    mkdir -p "$dir"
  fi
  
  cd "$dir" || fatal_error "Could not access $dir"
}

init_git() {
  log_header "Version Control"
  if ! git init > /dev/null; then
    log_warn "Git init failed. Skipped."
    return
  fi
  
  # Try to copy shared gitignore if it exists, otherwise use engine specific
  if [[ -f "$ARCHITECT_ROOT/resources/shared/.gitignore.template" ]]; then
    cp "$ARCHITECT_ROOT/resources/shared/.gitignore.template" ".gitignore"
  fi
}

finalize_git() {
  git add .
  git commit -m "chore: initial commit (generated by Architect)" > /dev/null 2>&1
  log_success "Project initialized with Git."
}
